### ISSUE TITLE
protocol error: frame with invalid size

### ISSUE THREAD

**Issue by bluejekyll** [carllerche/h2#283]
I'm running into this error with a default connection setup over rustls. The code is here: https://github.com/bluejekyll/trust-dns/pull/509

Specifically, the handshake construction is here: https://github.com/bluejekyll/trust-dns/blob/df05a26eb4839636b1124262c63ed440b2150e25/https/src/https_client_stream.rs#L396-L406

The request is built here: https://github.com/bluejekyll/trust-dns/blob/df05a26eb4839636b1124262c63ed440b2150e25/https/src/https_client_stream.rs#L60-L70

And Then the response stream is polled here: https://github.com/bluejekyll/trust-dns/blob/df05a26eb4839636b1124262c63ed440b2150e25/https/src/https_client_stream.rs#L206-L210

The `poll()` causes the error. Does it look like I'm doing anything obviously wrong?

**Comment by olix0r** [comment]
@bluejekyll can you include the output of the test with `RUST_LOG=h2::proto=trace`?

**Comment by bluejekyll** [comment]
Sure, I can enable the logging in the test and get that output.

**Comment by bluejekyll** [comment]
Ok, here we go:

```console
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running target/debug/deps/trust_dns_https-6c4da06a90fbe961

running 1 test
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::flow_control: inc_window; sz=65535; old=0; new=65535
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::flow_control: inc_window; sz=65535; old=0; new=65535
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::prioritize: Prioritize::new; flow=FlowControl { window_size: Window(65535), available: Window(65535) }
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::flow_control: inc_window; sz=65535; old=0; new=65535
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::flow_control: inc_window; sz=65535; old=0; new=65535
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::send: send_headers; frame=Headers { stream_id: StreamId(1), stream_dep: None, flags: HeadersFlag { end_stream: true, end_headers: true,padded: false, priority: false } }; init_window=65535
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::prioritize: schedule_send; StreamId(1)
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::store: Queue::push
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::store:  -> first entry
TRACE 2018-06-15T05:38:11Z: h2::proto::settings: send_pending_ack; pending=None
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::prioritize: try reclaim frame
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::prioritize: poll_complete
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::prioritize: schedule_pending_open
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::prioritize: pop_frame
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::prioritize: pop_frame; stream=StreamId(1); stream.state=State { inner: HalfClosedLocal(AwaitingHeaders) }
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::prioritize:  --> stream=StreamId(1); is_pending_reset=false;
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::prioritize: pop_frame; frame=Frame::Headers(Headers { stream_id: StreamId(1), stream_dep: None, flags: HeadersFlag { end_stream: true, end_headers: true, padded: false, priority: false } })
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::counts: transition_after; stream=StreamId(1); state=State { inner: HalfClosedLocal(AwaitingHeaders) }; is_closed=false; pending_send_empty=true; buffered_send_data=0; num_recv=0; num_send=1
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::prioritize: writing frame=Frame::Headers(Headers { stream_id: StreamId(1), stream_dep: None, flags: HeadersFlag { end_stream: true, end_headers: true, padded: false, priority: false } })
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::prioritize: try reclaim frame
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::prioritize: schedule_pending_open
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::prioritize: pop_frame
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::prioritize: try reclaim frame
TRACE 2018-06-15T05:38:11Z: h2::proto::settings: send_pending_ack; pending=None
DEBUG 2018-06-15T05:38:11Z: h2::proto::connection: Connection::poll; err=FRAME_SIZE_ERROR
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::state: recv_err; err=Proto(FRAME_SIZE_ERROR)
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::prioritize: clear_queue; stream-id=StreamId(1)
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::prioritize: assign_connection_capacity; inc=0
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::counts: transition_after; stream=StreamId(1); state=State { inner: Closed(LocallyReset(FRAME_SIZE_ERROR)) }; is_closed=true; pending_send_empty=true; buffered_send_data=0; num_recv=0; num_send=1
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::counts: dec_num_streams; stream=StreamId(1)
DEBUG 2018-06-15T05:38:11Z: h2::proto::connection: Connection::poll; err=FRAME_SIZE_ERROR
TRACE 2018-06-15T05:38:11Z: h2::proto::connection:     -> already going away
TRACE 2018-06-15T05:38:11Z: h2::proto::connection: connection closing after flush, reason=FRAME_SIZE_ERROR
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::streams: Streams::recv_eof
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::streams: drop_stream_ref; stream=Stream { id: StreamId(1), state: State { inner: Closed(LocallyReset(FRAME_SIZE_ERROR)) }, is_counted: false, ref_count: 2, next_pending_send: None, is_pending_send: false, send_flow: FlowControl { window_size: Window(65535), available: Window(0) }, requested_send_capacity: 0, buffered_send_data: 0, send_task: None, pending_send: Deque { indices: None }, next_pending_send_capacity: None, is_pending_send_capacity: false, send_capacity_inc: false, next_open: None, is_pending_open: false, next_pending_accept: None, is_pending_accept: false, recv_flow: FlowControl { window_size: Window(65535), available: Window(65535) }, in_flight_recv_data: 0, next_window_update: None, is_pending_window_update: false, reset_at: None, next_reset_expire: None, pending_recv: Deque { indices: None }, recv_task: None, pending_push_promises: Queue { indices: None, _p: PhantomData }, content_length: Omitted }
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::counts: transition_after; stream=StreamId(1); state=State { inner: Closed(LocallyReset(FRAME_SIZE_ERROR)) }; is_closed=true; pending_send_empty=true; buffered_send_data=0; num_recv=0; num_send=0
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::streams: drop_stream_ref; stream=Stream { id: StreamId(1), state: State { inner: Closed(LocallyReset(FRAME_SIZE_ERROR)) }, is_counted: false, ref_count: 1, next_pending_send: None, is_pending_send: false, send_flow: FlowControl { window_size: Window(65535), available: Window(0) }, requested_send_capacity: 0, buffered_send_data: 0, send_task: None, pending_send: Deque { indices: None }, next_pending_send_capacity: None, is_pending_send_capacity: false, send_capacity_inc: false, next_open: None, is_pending_open: false, next_pending_accept: None, is_pending_accept: false, recv_flow: FlowControl { window_size: Window(65535), available: Window(65535) }, in_flight_recv_data: 0, next_window_update: None, is_pending_window_update: false, reset_at: None, next_reset_expire: None, pending_recv: Deque { indices: None }, recv_task: None, pending_push_promises: Queue { indices: None, _p: PhantomData }, content_length: Omitted }
TRACE 2018-06-15T05:38:11Z: h2::proto::streams::counts: transition_after; stream=StreamId(1); state=State { inner: Closed(LocallyReset(FRAME_SIZE_ERROR)) }; is_closed=true; pending_send_empty=true; buffered_send_data=0; num_recv=0; num_send=0
thread 'https_client_stream::tests::test_https_cloudflare' panicked at 'send_message failed: Custom { kind: ConnectionAborted, error: StringError("recieved a stream error: protocol error: frame with invalid size") }', libcore/result.rs:945:5
stack backtrace:
   0:        0x10fde22cf - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h27c6a714b8afe2ad
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:        0x10fdd382d - std::sys_common::backtrace::print::h724ecea9caca7d00
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:        0x10fde52f3 - std::panicking::default_hook::{{closure}}::h80f09f812c6a3811
                               at libstd/panicking.rs:211
   3:        0x10fde507c - std::panicking::default_hook::he001e855112d1e1a
                               at libstd/panicking.rs:227
   4:        0x10fde5a1b - <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get::h9c190cf53a05bbf9
                               at libstd/panicking.rs:511
   5:        0x10fde57ee - std::panicking::continue_panic_fmt::h2006976ff93946c6
                               at libstd/panicking.rs:426
   6:        0x10fde5478 - std::panicking::try::do_call::ha766c418265acac4
                               at libstd/panicking.rs:337
   7:        0x10fe1a391 - core::ptr::drop_in_place::h19764bd83e2215e4
                               at libcore/panicking.rs:92
   8:        0x10fb09377 - <mio::event_imp::Ready as core::cmp::PartialEq>::eq::h0d1da9f2c20b935b
                               at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:26
   9:        0x10f7efbda - <core::result::Result<T, E>>::expect::hd2395d54819f3e2d
                               at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:809
  10:        0x10f817472 - trust_dns_https::https_client_stream::tests::test_https_cloudflare::h9e5adb7a539331a9
                               at https/src/https_client_stream.rs:498
  11:        0x10f834190 - trust_dns_https::__test::TESTS::{{closure}}::h32b5ba6ce7d01563
                               at https/src/https_client_stream.rs:464
  12:        0x10f801760 - core::ops::function::FnOnce::call_once::haf0c637d7be9dba2
                               at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
  13:        0x10f842b51 - <F as alloc::boxed::FnBox<A>>::call_box::ha380fe93ef3f0b8c
                               at libtest/lib.rs:1451
                               at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
                               at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:640
  14:        0x10fdf1a3e - panic_unwind::dwarf::eh::read_encoded_pointer::h425251e013531ef5
                               at libpanic_unwind/lib.rs:105
  15:        0x10f85f0b4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7c6d7c9ba2f383fb
                               at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:289
                               at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:374
                               at libtest/lib.rs:1406
                               at /Users/travis/build/rust-lang/rust/src/libstd/sys_common/backtrace.rs:136
  16:        0x10f863f87 - std::panicking::try::do_call::h3303a8237eccb668
                               at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:409
                               at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:305
                               at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:310
  17:        0x10fdf1a3e - panic_unwind::dwarf::eh::read_encoded_pointer::h425251e013531ef5
                               at libpanic_unwind/lib.rs:105
  18:        0x10f855164 - <F as alloc::boxed::FnBox<A>>::call_box::h5a99acfefc68f726
                               at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:289
                               at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:374
                               at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:408
                               at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:640
  19:        0x10fde4c07 - std::sys_common::thread::start_thread::h1b1392376f57151b
                               at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:650
                               at libstd/sys_common/thread.rs:24
  20:        0x10fdd28f8 - std::sys::unix::thread::Thread::new::thread_start::hb07e30b92faed9c5
                               at libstd/sys/unix/thread.rs:90
  21:     0x7fff639a3660 - _pthread_body
  22:     0x7fff639a350c - _pthread_start
test https_client_stream::tests::test_https_cloudflare ... FAILED

failures:

failures:
    https_client_stream::tests::test_https_cloudflare

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by olix0r** [comment]
thanks @bluejekyll .  i have a feeling that something is going wrong with the TLS handshake such that the stream that's built isn't actually an H2 stream (perhaps ALPN needs to be configured?)

To debug this, I'd probably use https://github.com/carllerche/io-dump to wrap the stream (i.e. that you pass into `handshake()`) to log the data as seen by the H2 codec.
